services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - docker build -t CItest .
        - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag citest $DOCKER_USERNAME/citest:$TRAVIS_BUILD_ID
        - docker push $DOCKER_USERNAME/citest
